on:
  push:
    branches:
      - main

jobs:
  update-translations-progress:
    name: Display translations progress inside readme.md
    runs-on: ubuntu-latest

    steps:
      - name: Update Translation Progress
        id: translation-progress-update
        uses: roules-dev/update-translation-progress-action@v1.0.0
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
